apiVersion: apps/v1
kind: Deployment
metadata:
  name: rockndogs-app
  namespace: rockndogs
  labels:
    app: rockndogs
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: rockndogs
  template:
    metadata:
      labels:
        app: rockndogs
        version: v1
    spec:
      # If your GHCR image is private, create a docker-registry secret and uncomment:
      # imagePullSecrets:
      #   - name: ghcr-pull-secret
      containers:
      - name: rockndogs
        image: ghcr.io/venkatal1611/rockndogs:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: rockndogs-secrets
              key: SESSION_SECRET
        envFrom:
        - configMapRef:
            name: rockndogs-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: rockndogs-service
  namespace: rockndogs
spec:
  type: NodePort
  selector:
    app: rockndogs
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
